import Script from "next/script";

export default function Head() {
  return (
    <>
      <title>Bingle 2: the next boogaloo</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by deez nuts lmao gottem" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
