import './globals.css';
import SideBar from './components/sidebar';

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<head />
			<body>
				<SideBar />
				{children}
			</body>
		</html>
	);
}

export const metadata = {
	title: 'Bingle2: the next boogaloo',
	description: 'Generated by deez nuts lmao gotem (Nextjs 13 beta)',
	icons: { icon: '/favicon.ico' },
};
